name: FeatureCI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 
    steps:
      - uses: actions/checkout@master

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm i

      - name: Lint
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm run lint

      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm run test
