name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: '15'
        env:
          SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
          SEO_URL: ${{ secrets.SEO_URL }}
          SEO_TWITTER_IMAGE: ${{ secrets.SEO_TWITTER_IMAGE }}
          SEO_TWITTER_ACCOUNT: ${{ secrets.SEO_TWITTER_ACCOUNT }}
      - run: npm ci
      - run: npm run test
      - run: npm run generate
      - run: npm install -g surge
      - run: surge ./dist/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Publish
        uses: nogsantos/ssh-scp-deploy@v1.2.1
        with:
          src: ./dist/*
          host: ${{ secrets.SCP_HOST }}
          remote: ${{ secrets.SCP_DIR }}
          port: ${{ secrets.SCP_PORT }}
          user: ${{ secrets.SCP_USER }}
          key: ${{ secrets.SCP_KEY }}
