name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm i
      - run: npm run test
      - run: npm run generate
      - run: npm install -g surge
      - run: surge ./dist/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Publish
        uses: horochx/deploy-via-scp@master
        with:
          local: ./dist/*
          remote: ${{ secrets.SCP_DIR }}
          host: ${{ secrets.SCP_HOST }}
          port: ${{ secrets.SCP_PORT }}
          user: ${{ secrets.SCP_USER }}
          key: ${{ secrets.SCP_KEY }}
